@startuml strategyの事例
skinparam groupInheritance 2


interface PaymentStrategy {
    +支払う()
}

class ICCardPayment implements PaymentStrategy {
    +支払う()
}

class CashPayment implements PaymentStrategy {
    +支払う()
}

class CouponPayment implements PaymentStrategy{
    -残りの回数
    +支払う()
}

class CommuterPassPayment implements PaymentStrategy{
    -期間
    +支払う()
}

class BusFarePayment {
    +支払い方法を設定する()
    +運賃を支払う()
}



BusFarePayment o-right-> PaymentStrategy


@enduml