@startuml test
class 事務 {

}

class システム利用者 {

}

class ダイヤ {

}

class 乗客 {

}

class スマホ {

}

class webアプリ {

}

class サーバー {

}

class 購入用外部システム {

}

class クレジット会社{

}

class 生協アプリ {

}

class チケット {

}

class 回数券 {

}

class 月利用券 {

}

class チケット読み取り機 {

}

class バス位置 {

}

class バス {

}

'関係'
事務 --> ダイヤ : 作成する
事務 --|> システム利用者
ダイヤ -- サーバー
webアプリ --> ダイヤ : 表示する
webアプリ -- 購入用外部システム
クレジット会社 --|> 購入用外部システム
生協アプリ --|> 購入用外部システム
購入用外部システム -- サーバー
乗客 --|> システム利用者
乗客 --> webアプリ : 利用する
乗客 -- スマホ
乗客 --> バス
スマホ --> チケット : 表示する
回数券 --|> チケット
月利用券 --|> チケット
チケット "*"--"1.." チケット読み取り機
バス o-- チケット読み取り機
バス --> バス位置
バス位置 "*"--"1" サーバー
サーバー <--> チケット読み取り機
サーバー -- チケット


@enduml
