@startuml 12回
'授業メモ'
'バグがあってプログラムだけの修正→設計書の変更を行っていない'
'長くソフトウェアを使うためには設計書とプログラムの相違がないようにしないといけない'


'クラス'
class 貸出し{
    -貸出し日
    -貸出し状況
    +貸出し中()
    +雑誌を借りられるかチェックする()
}

class 貸出し状態{

}

class 貸出中{

}

class 返却済み{

}

class 蔵書{
    -蔵書番号
    +妥当な蔵書()
    +本を購入する()
    +本を廃棄する()
}

class 書籍{
    -書名
    -著書
    -貸出し可能数
    +雑誌?()
}

class 雑誌{
    -号
    -巻
}

class 予約{
    -希望日
}

class 会員{
    -氏名
    -貸出し数
}

class 学生会員{
    -要注意人物か: boolean
}

class 教職員会員{
    -要注意人物か: boolean
}

'関係'
貸出し "0..1" -- "0..1" 予約
予約 -- 書籍
予約 "*" -- "1" 会員
蔵書 "*" -- "1" 書籍
貸出し "*" -- "1" 蔵書
貸出し "*" -- "1" 会員

会員 <|-- 学生会員
会員 <|-- 教職員会員
雑誌 --|> 書籍

貸出し状態 -- 貸出し
貸出し状態 <|-- 貸出中
貸出し状態 <|-- 返却済み
@enduml

