@startuml test
class 事務 {
    -登録者名
    +登録する()
}

class システム利用者 {
    -利用者ID

}

class ダイヤ {
}

class 乗客 {
    -乗客名
    +乗車下車する()
    +ダイヤを確認()
    +スマホをかざす()
}

class スマホ {
    -スマホID
    +チケットの表示()
}

class webアプリ {
    -利用者ID
    +ダイヤを確認する()
    +位置を確認する()
    +外部システムを利用する()
}

class サーバー {
    -サーバーID
    +保存する()
    +結果を返す()
    +位置を確認する()
    +チケットを更新する()
    +チケットを確認する()
}

class 購入用外部システム {
    +購入情報提供()
}

class クレジット会社{
    -クレジット会社ID
}

class 生協アプリ {
}

class チケット {
    -チケットID
}

class 回数券 {
    -残りの回数
}

class 月利用券 {
    -開始日
    -終了日
}

class チケット読み取り機 {
    -読み取り機ID
    +チケットを読み取る()
    +サーバーに通知する()
}

class バス位置 {
    -バスID
    -緯度経度
    -時刻
    +記録する()
}

class バス {
    -バスID
    -緯度経度
    +運行する()
    +報告する()
}

'関係'
事務 -right-|> システム利用者
乗客 -up-|> システム利用者

事務 --> ダイヤ : 作成する

ダイヤ -- サーバー
webアプリ -up-> ダイヤ : 表示する
webアプリ -left- 購入用外部システム
webアプリ --> チケット : 表示する
webアプリ -down- サーバー

クレジット会社 --|> 購入用外部システム
生協アプリ --|> 購入用外部システム
購入用外部システム -- サーバー

乗客 -down-> スマホ : 利用する
乗客 -right-> バス
スマホ -down-> webアプリ : ログインする 

回数券 -up-|> チケット
月利用券 -up-|> チケット
チケット -- チケット読み取り機
バス o-right- チケット読み取り機
バス --> バス位置
バス位置 -- サーバー
サーバー <--> チケット読み取り機
サーバー -- チケット


@enduml
