@startuml 8-2
title ユーザーに関するクラス図

'ユーザー管理に関連するクラス'

abstract class ユーザー {
    - ID
    - Password
    + システムにログインする()
    + オブザーバーの追加()
    + オブザーバーの削除()
}

class 学生 {
    - 名前
    - 学生番号
    - 所属学科
    + 科目を選択する()
    + 時間割を確認する()
    + 成績を確認する()
}

class 教員 {
    - 名前
    - 教職員番号
    + 成績登録する()
}

class ログイン管理 {
    - ログインログID
    + ID確認()
    + Password確認()
}

interface Observer_for_login{
    + 管理()
}

interface Subject_for_login{
    + オブザーバーの追加()
    + オブザーバーの削除()
}

ユーザー <|-down- 学生
ユーザー <|-down- 教員

Observer_for_login <.. ログイン管理
Observer_for_login <-right-o Subject_for_login
Subject_for_login <|-- ユーザー

@enduml