@startuml クラス図1
'分析段階のクラス図'


'クラス'
abstract ユーザー{
    - ID
    - Password
    + システムにログインする()
}

class 学生{
    - 名前
    - 学生番号
    + 履修登録する()
    + 履修削除する()
    + 時間割を確認する()
    + 成績を確認する()
}

class 教員{
    - 名前
    - 教職員番号
    + 成績登録する()
}

class 履修{
    - 履修番号
    - 学生番号
    - 科目
    - ステータス
    + 履修登録する()
    + 履修削除する()
}

class 科目一覧{
    - 学期
    - 曜日
    - 時間
    + 履修一覧を表示する()
    + 特定の条件の科目一覧を提供する()
    + 選択された科目を通知する()
}

class 科目{
    - 科目名
    - 科目コード
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間
}

class 成績{
    - 科目
    - 得点
    - 学生
    + 成績を表示する()
    + 成績を保存する()
}

class 学生一覧{

}

class 時間割{
    - 時間割番号
    - 学生
    + 表示する()
}

class 修得管理{
    - 履修一覧
    + 履修を促す()
}

class 報告管理{
    - 教員
    - 成績情報
    + 成績報告督促を送る()
    + 成績報告期限を送る()
}


'関係'
'ユーザー <|-down- 学生
'ユーザー <|-down- 教員

'教員 "1" --> "*" 科目 : 担当する
'教員 "1" --> "*" 成績 : 登録する
'教員 "1" <-- "*" 報告管理 : 通知する

'学生 "*" --> "1" 時間割 : 閲覧する
学生 "*" -down-> "1" 科目一覧 : 選択する
'学生 "*" --> "1" 成績 : 確認する
'学生 "1" <-- "1" 修得管理 : 通知する

'成績 "1" -right- "1" 報告管理
'科目 "1" -up- "1" 成績
科目一覧 -down-> 履修 : 通知する
'科目一覧 -- 科目
'履修 "1" -- "1" 修得管理
'履修 "*" -- "1" 科目
@enduml