@startuml クラス図1
'分析段階のクラス図'


'クラス'
abstract ユーザー{
    - ID
    - Password
    + システムにログインする()
}

'学生クラスは学生の名前や学生番号が属性として保存されている．
'科目の選択や時間割を確認等の動作を行う
class 学生{
    - 名前
    - 学生番号
    - 所属学科
    + 科目を選択する()
    + 時間割を確認する()
    + 成績を確認する()
}

'教員クラスは教員毎にオブジェクトが作成される
class 教員{
    - 名前
    - 教職員番号
    + 成績登録する()
}

'履修クラスはある学生がどの科目を履修しているかを表すクラスである．学生毎に作成されることを想定している
'このクラスで成績表や時間割が作成されることを想定している．
'成績クラスを参照し，成績も一緒に保存することを想定する
class 履修{
    - 履修番号
    - 学生番号
    - 学期
    + 科目が被っていないか確認()
    + 科目を登録する()
    + 履修を保存する()
}

'科目一覧クラスは科目クラスを参照し特定(曜日や時間)で合致する科目を一覧と表示や選択された科目を通知するクラスである．
class 科目一覧{
    + 履修一覧を表示する()
    + 特定の条件の科目一覧を提供する()
    + 履修登録する()
    + 履修削除する()
}

'担当科目一覧は教員が担当している科目を一覧として表示するために使用するクラスである．
class 担当科目一覧{
    - 教員ID
    + 担当科目を一覧として表示する()
    + 選択した科目を通知する()
}

class 履修者一覧{
    - 科目コード
    + 特定の科目の履修者一覧を作成する()
    + 表示する()
    + 成績を登録する()
}

'科目クラスには科目コード毎に作成される
'学期，曜日，時間等の情報が属性として保存されている．
'所属学科によって科目の分類が異なるので関連クラスとして定義されている
class 科目{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間
}

class 必修{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間
}

class 選択必修{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間  
}

class 選択{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間
}

class 成績{
    - 科目コード
    - 学生番号
    + 保存する()
    + 成績表を作成し表示する()
}

class 未登録{

}

class 仮登録{

}

class 本登録{

}

'履修クラスから作成され，学生から閲覧されることを想定している
class 時間割{
    - 時間割番号
    - 学生
    + 作成する()
    + 表示する()
}

'科目のうち必修クラスと履修クラスのステータスを確認し，修得できていなかったら修得を促すクラス
class 修得管理{
    + 修得状況を確認する()
    + 履修を促す()
}

class 報告管理{
    - 教員
    - 成績情報
    + 成績報告督促を送る()
    + 成績報告期限を送る()
}


'関係'
ユーザー <|-down- 学生
ユーザー <|-down- 教員

教員 "1" --> "*" 科目 : 担当する
教員 "1" --> "*" 担当科目一覧 : 選択する

学生 "*" --> "1" 時間割 : 閲覧する
学生 "*" --> "1" 科目一覧 : 選択する
学生 -- 履修
学生 "*" --> "1" 成績 : 閲覧する

成績 "1" -right- "1" 報告管理
履修者一覧 "1" -- "1" 成績
担当科目一覧 -- 履修者一覧
科目一覧 --> 履修 : 通知する

履修 --> 時間割 : 管理する
履修 --> 成績 : 管理する
履修 --> 履修者一覧 : 作成する

修得管理 --> 履修 : 確認する
修得管理 --> 必修 : 確認する

科目 <|-- 必修
科目 <|-- 選択必修
科目 <|-- 選択

成績 <|-- 未登録
成績 <|-- 仮登録
成績 <|-- 本登録
@enduml