@startuml クラス図1
'分析段階のクラス図'
left to right direction

'クラス'
class ユーザークラス{
    - ID
    - Password
    + ログインする()
}

class 学生{
    - 名前
    - 学生番号
    + ログインする()
    + 履修登録する()
    + 履修削除する()
}

class 教員{
    - 名前
    - 教職員番号
    + 成績登録する()
}

class 履修{
    - ステータス
    + 履修登録する()
    + 履修削除する()
}

class 履修可否{
    - 可否状態
    - 理由
    + 可否を判断する()
}

class 科目{
    - 科目コード
    - 担当教員
    - 学期
    - 曜日
    - 時間
}

class 成績{
    - 科目
    - 得点
    - 学生
}

class 時間割{
    - 科目
    - 学生
}

class 習得管理{
    - 履修一覧
    + 履修を促す()
}

class 報告管理{
    - 教員
    - 成績情報
    + 成績報告督促を送る()
    + 成績報告期限を送る()
}

class 通知{
    - 通知内容
    - 通知対象者
    - 通知日
    + 通知を送る
}


'関係'


@enduml