@startuml 6-3
title 時間割確認のシーケンス図
'クラス等
actor 学生 as foo1
participant 時間割 as foo3
participant 履修 as foo2


group 基本系列
    foo2 -> foo3 : 履修状況を反映する
    foo3 -> foo3 : 時間割を作成する
    foo1 -> foo3 : 時間割を閲覧する
end

@enduml