@startuml 6-2
title 履修削除のシーケンス図(使用なし)
'クラス等
actor 学生 as foo1
participant 科目検索 as foo2
participant 科目一覧 as foo3
participant 履修 as foo4

group 基本系列
    foo1 -> foo2 : 条件を選択する
    foo2 -> foo3 : 条件の科目を渡す
    foo3 -> foo1 : 表示する
    foo1 -> foo2 : 科目を選択する
    foo2 -> foo4 : 科目を履修登録する
    foo4 -> foo4 : 科目が他の履修登録された\n科目と被っていないか確認する
    foo4 -> foo4 : 科目を保存する
end

group 代替系列
    foo4 -> foo4 : 履修削除期間かの確認
    note left
        履修削除期間外だった場合
    end note
    foo4 -> foo1 : 期間外である旨を通知
end

@enduml