@startuml ユースケース図1
left to right direction

'アクター'
:学生: as A1
:教員: as A2


'ユースケース'
package システム{
    (学生用にログインする)  as U0
    (履修登録する) as U1
    (履修削除する) as U2
    (履修修正する) as U3
    (時間割を確認する) as U4
    (未習得の履修を促す) as U5
    (成績の報告をする) as U6
    (成績報告督促を送る) as U7
    (成績報告期限メールを送る) as U8
    (履修の可否を確認する) as U9
    (成績を確認する) as U10
    (教員用にログインする) as U11
}

'関係'
U0 --> U1
U0 --> U2 
U0 --> U3 
U0 --> U4 
U0 --> U10 
U1 ..> U9 : include

A1 -- U5
A1 --> U0

A2 --> U11
U11 --> U6 
A2 -- U7
A2 -- U8

@enduml