@startuml ユースケース図1
left to right direction

'アクター'
:学生: as A1
:教員: as A2
':事務: as A3'

'ユースケース'
package システム{
    (履修登録をする) as U1
    (履修登録削除する) as U2
    (履修登録修正する) as U3
    (時間割を確認する) as U4
    (成績を確認する) as U4
    (履修を促す) as U5
    (成績の報告をする) as U6
    (督促を送る) as U7
    (メールを送る) as U8
    (成績を確認する) as U9
}

'関係'
A1 --> U1
A1 --> U2
A1 --> U3
A1 --> U4
A1 --> U5
A1 --> U9

A2 --> U6


@enduml