@startuml ユースケース図1
left to right direction

'アクター'
:学生: as A1
:教員: as A2


'ユースケース'
package システム{
    (1.学生用にログインする)  as U0
    (2.履修登録する) as U1
    (3.履修削除する) as U2
    (4.履修修正する) as U3
    (5.時間割を確認する) as U4
    (7.未習得の履修を促す) as U5
    (9.成績の報告をする) as U6
    (10.成績報告督促を送る) as U7
    (11.成績報告期限メールを送る) as U8
    (12.履修の可否を確認する) as U9
    (6.成績を確認する) as U10
    (8.教員用にログインする) as U11
}

'関係'
U0 --> U1
U0 --> U2 
U1 ..> U3 : extend
U2 ..> U3 : extend
U0 --> U4 
U0 --> U10 
U1 ..> U9 : include

A1 -- U5
A1 --> U0

A2 --> U11
U11 --> U6 
A2 -- U7
A2 -- U8

@enduml