@startuml 5-4
title 教員に関するクラス図
'教員に関連するクラス'

class 教員{
    - 名前
    - 教員ID
    - 教職員番号
    + 成績登録する()
}

class 科目{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間
}

class 必修{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間
}

class 選択必修{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間  
}

class 選択{
    - 科目コード
    - 科目名
    - 担当教員
    - 単位数
    - 学期
    - 曜日
    - 時間
}

class 担当科目一覧{
    - 教員ID
    + 担当科目を一覧として表示する()
    + 選択した科目を通知する()
}

class 成績 {
    - 科目コード
    - 学生番号
    - 点数
    + 保存する()
    + 成績表を作成し表示する()
}

class 成績表 {
    - 学生番号
    + 成績表を作成する()
    + 成績表を表示する()
}

class 報告管理 {
    - 教員
    - 成績情報
    + 成績登録状況を確認する()
    + 成績報告督促を送る()
    + 成績報告期限を送る()
}

class 履修者一覧 {
    - 科目コード
    + 特定の科目の履修者一覧を作成する()
    + 表示する()
    + 成績を登録する()
}

class 未登録{

}

class 仮登録{

}

class 本登録{

}

教員 "1"-->"1" 担当科目一覧 : 選択する
教員 "1"-left->"*" 科目 : 担当する
担当科目一覧 "1"-->"1" 履修者一覧 
履修 "*"-->"1" 履修者一覧 : 作成する
履修者一覧 "1"-->"*" 成績 : 登録する
成績 "*"-left->"1" 成績表 : 管理する
成績 "*"-right-"1" 報告管理

成績 <|-- 未登録
成績 <|-- 仮登録
成績 <|-- 本登録

科目 <|-- 必修
科目 <|-- 選択必修
科目 <|-- 選択

@enduml
