@startuml 5-3
title 学生に関するクラス図

'学生に関連するクラス
class 学生{
    - 名前
    - 学生番号
    - 所属学科
    + 科目を選択する()
    + 時間割を確認する()
    + 成績を確認する()
}

class 履修 {
    - 履修番号
    - 学生番号
    - 学期
    + 科目が被っていないか確認()
    + 科目を登録する()
    + 履修を保存する()
}

class 科目検索 {
    + 条件に合う科目を検索する()
    + 選択された科目を認識する()
}

class 科目一覧 {
    + 科目一覧を表示する()
}

class 修得管理 {
    + 修得状況を確認する()
    + 履修を促す()
}

class 成績表{
    - 学生番号
    + 成績表を作成する
    + 成績表を表示する
}

class 時間割{
    - 時間割番号
    - 学生
    + 作成する()
    + 表示する()
}

学生 "*"-->"*" 科目検索
学生 "*"-->"1" 時間割
学生 "*"-->"1" 成績表
科目検索 "1"-right-"1" 科目一覧
科目検索 "1"-->"1" 履修 : 登録，削除する
履修 "*"-right-"1" 修得管理

@enduml