@startuml 9-1
title ユーザー管理機能

'ユーザー管理に関連するクラス'

abstract class ユーザー {
    - ID
    - Password
    + システムにログインする()
}

class 学生 {
    - 名前
    - 学生番号
    - 所属学科
    + 科目を選択する()
    + 時間割を確認する()
    + 成績を確認する()
}

class 教員 {
    - 名前
    - 教職員番号
    + 成績登録する()
}

class ログイン管理 {
    - ログインログID
    + ID確認()
    + Password確認()
}

ユーザー <|-down- 学生
ユーザー <|-down- 教員
ユーザー -right- ログイン管理

@enduml