@startuml 8-1
title 履修登録時のシステムの\nステートマシン図
[*] --> 初期状態 : システム起動

初期状態 --> 条件選択中

state 条件選択中 {
    [*] --> 科目検索 : 曜日，時間を選択する
}

条件選択中 --> 科目選択中

科目選択中 --> 履修登録中

state 履修登録中 {
  [*] --> 登録完了 : 登録が完了する
  [*] --> 登録失敗 : 登録に失敗する
}

履修登録中 --> [*]
@enduml