@startuml 7-2
title 履修登録，削除のアクティビティ図

|学生|
start
:曜日，時間を選択;

|システム|
:科目一覧を表示;

|学生|
:科目を選択;

|システム|
if (その科目が登録されているか) then (no)
    if (履修登録できるか？) then (no)
        :履修登録不可能と表示;
        stop
    else (yes)
        :科目を登録;
        :履修登録完了のメッセージを表示;
    endif



else (yes)
    |システム|
    if (履修削除期間か？) then (no)
        :履修削除期間外である\nメッセージを表示;
        stop
    else (yes)
        :科目を削除;
        :履修削除完了のメッセージ表示;
    endif
endif

|学生|
:登録内容を確認;
end

@enduml