@startuml 7-1
title ログインするのアクティビティ図

|学生|
start
:ID，Passwordを入力;

|システム|
if (ID，Passwordが合っているか？) then (yes)
    :ログインを許可する;
else (no)
    :ID又はPasswordが\n異なっていると表示;
    stop
endif

:ログインする;
end
@enduml