@startuml 7-3
title 履修削除のアクティビティ図(使用しない)

|学生|
start
:曜日，時間を選択;

|システム|
:科目一覧を表示;

|学生|
:科目を選択;

|システム|
if (履修削除期間であるか？) then (yes)
    :科目を削除する;
    :通知する;
else (no)
    :履修削除期間外であることを表示する;
    stop
endif

|学生|
:削除内容を確認;
end
@enduml