@startuml 7-5
title 成績を登録する

|システム|
start
:教員が担当している科目を表示する;

|教員|
:科目を選択する;

|システム|
:科目の履修者を表示する;

|教員|
repeat :履修者に対して成績を入力する;

:成績を保存を選択する;

|システム|
:仮成績として保存する;

|教員|
repeat while (すべての履修者に対して\n成績が登録されているか？) is (no) not (yes)
:成績を登録を選択する;

|システム|
:本成績として保存する;

end
@enduml